version: '3.6'
services:
  ## DB
  db:
    image: "postgres:14"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - db_store:/var/lib/postgresql/data
      - $PWD/dumps:/dumps

  ## APP
  app:
    build:
      context: .
      target: development
    image: 'podcast-app:development'
    command: '/bin/bash -c "while true; do sleep 10; done;"'
    volumes:
      - "$PWD:/rails"
      - bundle_store:/usr/local/bundle
    ports:
      - "3300:3000"
    depends_on:
      - db
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_USER=postgres"

volumes:
  db_store: {}
  bundle_store: {}

